### ISSUE TITLE
lint-trap + sublime linter

### ISSUE THREAD

**Issue by Raynos** [uber/lint-trap#59]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Unexpected "e" at position 0 in state START
    at Parser.proto.charError (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/jsonstream2/node_modules/jsonparse/jsonparse.js:89:16)
    at Parser.proto.write (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/jsonstream2/node_modules/jsonparse/jsonparse.js:118:23)
    at DestroyableTransform._transform (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/jsonstream2/src/jsonstream2.js:34:12)
    at DestroyableTransform.Transform._read (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/home/raynos/projects/nvm/v0.10.26/lib/node_modules/lint-trap/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (_stream_readable.js:583:24)
    at flow (_stream_readable.js:592:7) 
```

When running lint-trap from sublime sometimes this happens. not really sure what that means

**Comment by malandrew** [comment]
Pretty sure this is fixed by https://github.com/uber/lint-trap/pull/88
